name: Autograde R Assignment

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student code
        uses: actions/checkout@v3
        
      - name: Checkout private tests
        uses: actions/checkout@v3
        with:
          repository: r-classes-2025/r-grading-tests
          token: ${{ secrets.TEST_REPO_TOKEN }}  
          path: private-tests
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
         extra-packages: |
          dplyr
          purrr
          xml2
          testthat
          
      - name: Run tests
        run: Rscript private-tests/run_tests.R
    